/**
 * `toTailwindTheme` — Tailwind v4's `@theme` block is the primary target;
 * v3's JS config object is legacy but still widely deployed (§37).
 *
 * v4: the same raw `:root`/dark value blocks as `toCssVars`, plus an
 * `@theme inline { --color-<role>: var(--<role>) }` bridge so Tailwind's own
 * utilities (`bg-primary`, `text-sidebar-foreground`, …) resolve against
 * whichever block is active.
 *
 * v3: a `tailwind.config.js` fragment that maps every role to a bare
 * `var(--role)` reference. Unlike the other serializers, this output does
 * not depend on the *tree's* values at all — only on which roles exist,
 * which is fixed at compile time. That's deliberate, not an oversight: a
 * Tailwind v3 config is a build-time file, so the only way one static
 * config can serve every tenant is for it to defer to whichever CSS custom
 * properties are inlined at request time (§3), never to bake a value in.
 */

import type { TokenTree } from '../../shared/types/index.js';
import { CHART_ROLE_ORDER, COLOR_ROLE_ORDER } from './roles.js';
import { declaration, resolveMode, wrapDarkRule, type DarkModeStrategy } from './shared.js';

export interface TailwindOpts {
  /** @default 4 */
  version?: 3 | 4;
  /** @default 'attribute' — v4 only. */
  darkMode?: DarkModeStrategy;
  /** @default ':root' — v4 only. */
  selector?: string;
  /** Strips the newline between blocks — v4 only; the v3 config is always pretty-printed. @default false */
  minify?: boolean;
}

function colorDeclarations(tree: TokenTree, scheme: 'light' | 'dark'): string {
  const decls: string[] = [];
  for (const role of COLOR_ROLE_ORDER) decls.push(declaration(role, resolveMode(tree.color[role], scheme)));
  for (const role of CHART_ROLE_ORDER) decls.push(declaration(role, resolveMode(tree.chart[role], scheme)));
  return decls.join('');
}

function toTailwindV4Theme(tree: TokenTree, opts: TailwindOpts): string {
  const selector = opts.selector ?? ':root';
  const darkMode = opts.darkMode ?? 'attribute';
  const minify = opts.minify ?? false;

  const lightDecls = colorDeclarations(tree, 'light') + declaration('radius', resolveMode(tree.shape.radius, 'light'));
  const lightRule = `${selector}{${lightDecls}}`;
  const darkRule = wrapDarkRule(selector, darkMode, colorDeclarations(tree, 'dark'));

  const mappings = [...COLOR_ROLE_ORDER, ...CHART_ROLE_ORDER]
    .map((role) => `--color-${role}:var(--${role});`)
    .join('');
  const themeBlock = `@theme inline{${mappings}--radius:var(--radius);}`;

  const sep = minify ? '' : '\n';
  return `${themeBlock}${sep}${lightRule}${sep}${darkRule}`;
}

/**
 * Flat keys (`'sidebar-primary-foreground'`) rather than shadcn's nested
 * `{ DEFAULT, foreground }` groups. Both are valid Tailwind v3 config shapes
 * and both produce the same utility class names (`bg-sidebar-primary-foreground`
 * either way) — flat avoids a whole class of "did I nest this one right" bugs
 * for no loss of functionality.
 */
function toTailwindV3Config(): string {
  const colorLines = [...COLOR_ROLE_ORDER, ...CHART_ROLE_ORDER]
    .map((role) => `        '${role}': 'var(--${role})',`)
    .join('\n');

  return [
    '/** Generated by @pxlhut/brand-core. Merge into tailwind.config.js under theme.extend. */',
    'module.exports = {',
    '  theme: {',
    '    extend: {',
    '      colors: {',
    colorLines,
    '      },',
    "      borderRadius: { DEFAULT: 'var(--radius)' },",
    '    },',
    '  },',
    '};',
    '',
  ].join('\n');
}

export function toTailwindTheme(tree: TokenTree, opts: TailwindOpts = {}): string {
  const version = opts.version ?? 4;
  return version === 3 ? toTailwindV3Config() : toTailwindV4Theme(tree, opts);
}
